### ISSUE TITLE
Object #<ConnectResponse> has no method 'error'

### ISSUE THREAD

**Issue by bobrik** [dannycoates/zkjs#14]
This is what happens:

```
/blah/blah/blah/node_modules/zkjs/receiver.js:88
                        response.error(this.state.xid)
                                 ^
TypeError: Object #<ConnectResponse> has no method 'error'
    at Receiver.read (/blah/blah/blah/node_modules/zkjs/receiver.js:88:16)
    at Receiver.streamReadable (/blah/blah/blah/node_modules/zkjs/receiver.js:112:8)
    at Client.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
    at readableAddChunk (_stream_readable.js:150:9)
    at Client.Readable.push (_stream_readable.js:113:10)
    at TCP.onread (net.js:511:21)
```

Unfortunately i cannot extract small piece of code to reproduce that, but it happens in my code when i call start for started session. Btw, missing method is a problem for sure.

**Comment by aleafs** [comment]
+1
