### ISSUE TITLE
node0.10+ : TypeError: Cannot read property 'flowing' of undefined

### ISSUE THREAD

**Issue by fengmk2** [dannycoates/zkjs#6]
TypeError: Cannot read property 'flowing' of undefined

``` js
$ node zk.js 

_stream_readable.js:655
  if (ev === 'data' && !this._readableState.flowing)
                                           ^
TypeError: Cannot read property 'flowing' of undefined
    at Client.Readable.on (_stream_readable.js:655:44)
    at Readable.wrap (/Users/mk2/git/node-hbase-client/node_modules/zkjs/node_modules/readable-stream/lib/_stream_readable.js:749:10)
    at new Client (/Users/mk2/git/node-hbase-client/node_modules/zkjs/client.js:12:14)
    at Ensemble.connect (/Users/mk2/git/node-hbase-client/node_modules/zkjs/ensemble.js:43:17)
    at Session.start (/Users/mk2/git/node-hbase-client/node_modules/zkjs/session.js:92:17)
    at Object.<anonymous> (/Users/mk2/git/node-hbase-client/zk.js:16:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by fengmk2** [comment]
@dannycoates

**Comment by fengmk2** [comment]
Test codes:

``` js
var ZK = require('zkjs')

var zk = new ZK({
    hosts: ['localhost:2181', 'localhost:2182', 'localhost:2183'],
    root: '/myapp/root'
})

zk.start(function (err) {

    zk.create(
        '/foo',
        'some ephemeral data',
        ZK.create.EPHEMERAL,
        function (err, path) {
            if (!err) {
                console.log(path, 'was created')
            }
        }
    )

    zk.getChildren(
        '/',
        function (err, children, zstat) {
            if (!err) {
                console.log('/', 'has', children.length, 'children')
            }
        }
    )

    zk.get(
        '/some/known/node',
        function (watch) {
            console.log(watch.path, 'was', watch.type)
        },
        function (err, value, zstat) {
            console.log('the current value is ', value.toString())

            zk.set(
                '/some/known/node',
                'some new data',
                zstat.version,
                function (err, zstat) {
                    if (!err) {
                        console.log('the new version number is', zstat.version)
                    }
                }
            )
        }
    )
})
```
